"""add PPE compliance fields

Revision ID: 26c023d2c0e2
Revises: 1d4081b36232
Create Date: 2026-08-17 21:24:27.247226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c023d2c0e2'
down_revision: Union[str, Sequence[str], None] = '1d4081b36232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detections', sa.Column('helmet_compliant', sa.Boolean(), nullable=True))
    op.add_column('detections', sa.Column('vest_compliant', sa.Boolean(), nullable=True))
    op.add_column('detections', sa.Column('boots_compliant', sa.Boolean(), nullable=True))
    op.add_column('detections', sa.Column('is_compliant', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detections', 'is_compliant')
    op.drop_column('detections', 'boots_compliant')
    op.drop_column('detections', 'vest_compliant')
    op.drop_column('detections', 'helmet_compliant')
    # ### end Alembic commands ###
