"""rename image path columns

Revision ID: 74ce3aa91169
Revises: c3c288ddaaa3
Create Date: 2026-07-02 18:41:07.101217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ce3aa91169'
down_revision: Union[str, Sequence[str], None] = 'c3c288ddaaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_jobs', sa.Column('raw_image_path', sa.Text(), nullable=False))
    op.add_column('image_jobs', sa.Column('processed_image_path', sa.Text(), nullable=True))
    op.drop_column('image_jobs', 'local_processed_path')
    op.drop_column('image_jobs', 'local_raw_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_jobs', sa.Column('local_raw_path', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('image_jobs', sa.Column('local_processed_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('image_jobs', 'processed_image_path')
    op.drop_column('image_jobs', 'raw_image_path')
    # ### end Alembic commands ###
