"""initial schema

Revision ID: c3c288ddaaa3
Revises: 
Create Date: 2026-07-02 17:54:27.707063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3c288ddaaa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('camera_id', sa.String(length=64), nullable=False),
    sa.Column('remote_url', sa.Text(), nullable=False),
    sa.Column('local_raw_path', sa.Text(), nullable=False),
    sa.Column('local_processed_path', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('processing_duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'DOWNLOADING', 'DOWNLOADED', 'VALIDATING', 'PROCESSING', 'PROCESSED', 'DELIVERED', 'FAILED', name='imagestatus'), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_jobs_camera_id'), 'image_jobs', ['camera_id'], unique=False)
    op.create_index(op.f('ix_image_jobs_delivery_status'), 'image_jobs', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_image_jobs_sha256'), 'image_jobs', ['sha256'], unique=False)
    op.create_index(op.f('ix_image_jobs_status'), 'image_jobs', ['status'], unique=False)
    op.create_table('detections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('image_job_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x_min', sa.Integer(), nullable=False),
    sa.Column('y_min', sa.Integer(), nullable=False),
    sa.Column('x_max', sa.Integer(), nullable=False),
    sa.Column('y_max', sa.Integer(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_job_id'], ['image_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_image_job_id'), 'detections', ['image_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_image_job_id'), table_name='detections')
    op.drop_table('detections')
    op.drop_index(op.f('ix_image_jobs_status'), table_name='image_jobs')
    op.drop_index(op.f('ix_image_jobs_sha256'), table_name='image_jobs')
    op.drop_index(op.f('ix_image_jobs_delivery_status'), table_name='image_jobs')
    op.drop_index(op.f('ix_image_jobs_camera_id'), table_name='image_jobs')
    op.drop_table('image_jobs')
    # ### end Alembic commands ###
